name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install pulseaudio on ubuntu
        if: matrix.os == 'ubuntu-22.04'
        run: sudo apt-get install pulseaudio libpulse-dev libasound-dev

      - uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0

      - name: Run zig fmt
        if: matrix.os == 'ubuntu-22.04'
        run: zig fmt --check .

      - name: Build zenpaper
        run: zig build
